# Generated by Django 6.0.4 on 2026-04-22 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "effort_minutes",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (30, "<1h"),
                            (90, "1-2h"),
                            (240, "2-6h"),
                            (480, "1d"),
                            (960, ">1d"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "want"),
                            (2, "should"),
                            (3, "could"),
                            (4, "whatev"),
                            (5, "lol"),
                        ],
                        default=3,
                    ),
                ),
                ("is_highlighted", models.BooleanField(db_index=True, default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("wip", "In progress"),
                            ("blocked", "Blocked"),
                            ("completed", "Completed"),
                            ("wontfix", "Won't fix"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=10,
                    ),
                ),
                ("blocked_reason", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("github", "GitHub"),
                            ("claude", "Claude"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "order_in_milestone",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                (
                    "order_in_priority",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                (
                    "assignee",
                    models.CharField(blank=True, db_index=True, max_length=200),
                ),
                ("interested_parties", models.JSONField(blank=True, default=list)),
                ("links", models.JSONField(blank=True, default=list)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": [
                    "priority",
                    "-is_highlighted",
                    "order_in_milestone",
                    "-created_at",
                ]
            },
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"ordering": ["-target_date"]},
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="core.issue",
                    ),
                ),
            ],
            options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="issue",
            name="milestone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issues",
                to="core.milestone",
            ),
        ),
        migrations.CreateModel(
            name="GithubRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("issue", "Issue"),
                            ("pr", "Pull Request"),
                            ("commit", "Commit"),
                        ],
                        max_length=10,
                    ),
                ),
                ("repo", models.CharField(max_length=200)),
                ("number", models.IntegerField(blank=True, null=True)),
                ("sha", models.CharField(blank=True, max_length=40)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("state", models.CharField(blank=True, max_length=20)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github_refs",
                        to="core.issue",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("kind__in", ["issue", "pr"]), ("number__isnull", False)
                            ),
                            models.Q(
                                ("kind", "commit"), models.Q(("sha", ""), _negated=True)
                            ),
                            _connector="OR",
                        ),
                        name="githubref_kind_consistency",
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="IssueReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references_from",
                        to="core.issue",
                    ),
                ),
                (
                    "to_issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references_to",
                        to="core.issue",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("from_issue", "to_issue"), name="unique_issue_ref"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("from_issue", models.F("to_issue")), _negated=True
                        ),
                        name="no_self_ref",
                    ),
                ]
            },
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["status", "priority"], name="core_issue_status_abe731_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["milestone", "order_in_milestone"],
                name="core_issue_milesto_a59516_idx",
            ),
        ),
    ]
