# Generated by Django 6.0.4 on 2026-04-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0004_apitoken")]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="priority",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "jetzt"),
                    (1, "will"),
                    (2, "sollte"),
                    (3, "könnte"),
                    (4, "egal"),
                    (5, "lol"),
                ],
                default=3,
            ),
        )
    ]
