# Generated by Django 6.0.4 on 2026-07-09 22:22

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0005_alter_issue_priority")]

    operations = [
        migrations.CreateModel(
            name="SpecSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("claude_session_id", models.UUIDField(default=uuid.uuid4)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("explore", "Explore"),
                            ("propose", "Propose"),
                            ("ready", "Ready"),
                        ],
                        db_index=True,
                        default="explore",
                        max_length=10,
                    ),
                ),
                (
                    "issue",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spec_session",
                        to="core.issue",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="SpecTurn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("chat", "Chat"), ("critique", "Critique")],
                        default="chat",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("explore", "Explore"),
                            ("propose", "Propose"),
                            ("ready", "Ready"),
                        ],
                        max_length=10,
                    ),
                ),
                ("claude_session_id", models.UUIDField(blank=True, null=True)),
                ("prompt_sent", models.TextField(blank=True)),
                ("response", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("raw_result", models.JSONField(blank=True, default=dict)),
                (
                    "cost_usd",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("artifacts", models.JSONField(blank=True, default=dict)),
                ("error_detail", models.TextField(blank=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="core.specsession",
                    ),
                ),
            ],
            options={"ordering": ["created_at", "pk"]},
        ),
    ]
