# Generated by Django 6.0.4 on 2026-07-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0006_specsession_specturn")]

    operations = [
        migrations.AddField(
            model_name="specturn",
            name="actor",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="specturn",
            name="kind",
            field=models.CharField(
                choices=[("chat", "Chat"), ("critique", "Critique"), ("push", "Push")],
                default="chat",
                max_length=10,
            ),
        ),
    ]
